/*
 * PetStore
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2019-12-04T02:15:00Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
    "log"

    "github.com/apex/gateway"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/apollo-anonymous-demo/test-lambda/go"
)

func main() {
	log.Printf("Lambda Invoked")

	router := sw.NewRouter()

    log.Fatal(gateway.ListenAndServe("We are a Lambda", router))
}
